# NUMPY. Numerical Computing with Python

Python language is an excellent tool for general-purpose programming, with a highly readable syntax, rich and powerful data types and totally Zen:

In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


---

However, it was not designed specifically for mathematical and scientific computing.
In particular, Python lists are very flexible containers, but they are poorly suited to represent efficiently common mathematical constructs like vectors and matrices. 

Fortunately, exists the **numpy** package (module) which is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), performance is very good. It is used in almost all numerical computation using Python.



Why not simply use Python lists for computations instead of creating a new array type?

There are several reasons:

* Python lists are very general. They can contain any kind of object. They are dynamically typed. They do not support mathematical functions such as matrix and dot multiplications, etc. Implementating such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are statically typed and homogeneous. The type of the elements is determined when array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of numpy arrays can be implemented in a compiled language (C and Fortran is used).


##Basics of Numpy

To use **numpy** it is needed to import the module:

In [2]:
import numpy as np

##Creating numpy arrays
There are a number of ways to initialize new numpy arrays, for example from

1. A Python list or tuples
2. Using array-generating functions, such as `arange`, `linspace`, etc.
3. Reading data from files

###1. From a list
For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.

In [4]:
# a vector: the argument to the array function is a Python list
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [4]:
# a matrix: the argument to the array function is a nested Python list
M = np.array([[1, 2], [3, 4]])
M

array([[1, 2],
       [3, 4]])

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [18]:
M = np.array([[1, 2], [3, 4]], dtype=complex)
M

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

Common type that can be used with dtype are: int, float, complex, bool, object, etc.

We can also explicitly define the bit size of the data types, for example: int64, int16, float128, complex128.

###2. Using array-generating functions
For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generates arrays of different forms. Some of the more common are:

**Zeros and Ones**

In [12]:
np.zeros(5, dtype=float)

array([ 0.,  0.,  0.,  0.,  0.])

In [13]:
np.ones(5,dtype=float)

array([ 1.,  1.,  1.,  1.,  1.])

In [14]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

**arange**

In [22]:
x = np.arange(-10, 20, 4) # arguments: start, stop, step
x

array([-10,  -6,  -2,   2,   6,  10,  14,  18])

**linspace and logspace**

In [23]:
print "A linear grid between 0 and 1:"
print np.linspace(0, 1, 5)


A linear grid between 0 and 1:
[ 0.    0.25  0.5   0.75  1.  ]


In [11]:
print "A logarithmic grid between 10**0 and 10**3:"
print np.logspace(0, 3, 10)

A logarithmic grid between 10**0 and 10**3:
[    1.             2.15443469     4.64158883    10.            21.5443469
    46.41588834   100.           215.443469     464.15888336  1000.        ]


**Creating random arrays**

In [24]:
# uniform random numbers in [0,1]
np.random.rand(5,5)

array([[ 0.50253451,  0.67724281,  0.36682038,  0.46608401,  0.8462209 ],
       [ 0.60522014,  0.448527  ,  0.42201451,  0.07985599,  0.23631079],
       [ 0.96804171,  0.71534631,  0.52083378,  0.26481187,  0.27042867],
       [ 0.16719192,  0.47484002,  0.01323083,  0.83245629,  0.82883179],
       [ 0.50996872,  0.24565288,  0.91456804,  0.96485079,  0.9734772 ]])

In [27]:
# 5 samples from a normal distribution with a mean of 10 and a variance of 3:
np.random.normal(10, 3, 5)

array([ 16.25760171,  11.75213111,  15.88614589,  12.68018594,   2.97440005])

** diag **

In [26]:
# a diagonal matrix
np.diag([1,1,10,1])

array([[ 1,  0,  0,  0],
       [ 0,  1,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0,  1]])

###3.  Reading data from files


** Comma-separated values (CSV) **

A very common file format for data files are the comma-separated values (CSV), or related format such as TSV (tab-separated values).
Open data from https://github.com/datasets

[vix-daily.csv](https://raw.githubusercontent.com/datasets/finance-vix/master/data/vix-daily.csv)


In [15]:
# Open data from https://github.com/datasets
data = np.genfromtxt('https://raw.githubusercontent.com/datasets/finance-vix/master/data/vix-daily.csv'\
                     ,skip_header=1,delimiter=',')
data

array([[   nan,  17.96,  18.68,  17.54,  18.22],
       [   nan,  18.45,  18.49,  17.44,  17.49],
       [   nan,  17.66,  17.67,  16.19,  16.73],
       ..., 
       [   nan,  15.49,  16.43,  15.18,  16.31],
       [   nan,  16.44,  17.56,  16.08,  16.71],
       [   nan,  16.7 ,  17.98,  15.9 ,  16.16]])

*Few remarks on NANs:*

By definition, NaN is a float point number which is not equal to any other number 


In [16]:
np.nan != np.nan

True

In [17]:
data== np.nan

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       ..., 
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [18]:
np.isnan(data)

array([[ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       ..., 
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False]], dtype=bool)

In [19]:
help('numpy.genfromtxt')

Help on function genfromtxt in numpy:

numpy.genfromtxt = genfromtxt(fname, dtype=<type 'float'>, comments='#', delimiter=None, skiprows=0, skip_header=0, skip_footer=0, converters=None, missing='', missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file or str
        File, filename, or generator to read.  If the filename extension is
        `.gz` or `.bz2`, the file is first decompressed. Note that
        generators must return byte strings in Python 3k.
    dtype : dtype, optional
        Data type of the resulting arr

In [21]:
# Open data from https://github.com/datasets
data = np.genfromtxt('https://raw.githubusercontent.com/datasets/finance-vix/master/data/vix-daily.csv'\
                     ,skip_header=1,delimiter=',',usecols=[1,2,3,4])
!head vix-daily.csv
data

array([[ 17.96,  18.68,  17.54,  18.22],
       [ 18.45,  18.49,  17.44,  17.49],
       [ 17.66,  17.67,  16.19,  16.73],
       ..., 
       [ 15.49,  16.43,  15.18,  16.31],
       [ 16.44,  17.56,  16.08,  16.71],
       [ 16.7 ,  17.98,  15.9 ,  16.16]])

Using `numpy.savetxt` we can store a Numpy array to a file in CSV format:

In [22]:
M = np.random.rand(3,3)
np.savetxt("random-matrix.csv", M, delimiter=',')
%cat random-matrix.csv

1.986789867158184064e-01,2.807977895704615312e-01,9.121693836187327875e-02
4.732098731602899511e-01,6.734815087619171470e-01,4.808308879810230252e-02
5.443817005178985813e-01,1.906274437302658553e-01,6.136591566396684128e-01


In [24]:
np.savetxt("random-matrix.csv", M, fmt='%.5f', delimiter= ',') # fmt specifies the format
%cat random-matrix.csv

0.19868,0.28080,0.09122
0.47321,0.67348,0.04808
0.54438,0.19063,0.61366


To read data from such file into Numpy arrays we can use the `numpy.genfromtxt` function.


In [25]:
data = np.genfromtxt('random-matrix.csv',delimiter=',')
data

array([[ 0.19868,  0.2808 ,  0.09122],
       [ 0.47321,  0.67348,  0.04808],
       [ 0.54438,  0.19063,  0.61366]])

** Numpy's native file format **

In [26]:
np.save("random-matrix.npy", M)
!file random-matrix.npy

random-matrix.npy: data


In [27]:
np.load("random-matrix.npy")

array([[ 0.19867899,  0.28079779,  0.09121694],
       [ 0.47320987,  0.67348151,  0.04808309],
       [ 0.5443817 ,  0.19062744,  0.61365916]])

##Manipulating arrays


In [28]:
lst = [10, 20, 30, 40]
arr = np.array([10, 20, 30, 40],dtype='int64')
M = np.array([[10, 20, 30, 40],[50, 60, 70, 80]])

** Element indexing **


In [29]:
#get the first element of list
lst[0]

10

In [30]:
#get the first element of array
arr[0]

10

In [42]:
# M is a matrix, or a 2 dimensional array, taking two indices 
print M[0,0] # element from first row first column 
print M[1,1] # element from second row second column

10
60


If we omit an index of a multidimensional array it returns the whole row
(or, in general, a N-1 dimensional array)

In [32]:
M[1] # second row

array([50, 60, 70, 80])

The same thing can be achieved with using `:` instead of an index: 

In [33]:
M[1,:] # second row, all columns 

array([50, 60, 70, 80])

In [34]:
M[:,1] # all rows, second column 

array([20, 60])

We can assign new values to elements in an array using indexing:

In [43]:
M[0,0] = 1
M

array([[ 1, 20, 30, 40],
       [50, 60, 70, 80]])

In [44]:
# also works for rows and columns
M[1,:] = 0
M[:,2] = -1
M

array([[ 1, 20, -1, 40],
       [ 0,  0, -1,  0]])

Arrays are homogeneous; i.e. all elements of an array must be of the same type


In [45]:
#Lists are heterogeneous
lst[1] = 'a string inside a list'
lst


[10, 'a string inside a list', 30, 40]

In [46]:
#Arrays are homogeneous
arr[1] = 'a string inside an array'

ValueError: invalid literal for long() with base 10: 'a string inside an array'

Once an array has been created, its dtype is fixed and it can only store elements of the same type. For this example where the dtype is integer, if we store a floating point number it will be automatically converted into an integer:

In [47]:
arr[1] = 1.234
arr

array([10,  1, 30, 40])

** Index slicing **

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [48]:
A = np.array([1,2,3,4,5])
#slice from second to fourth element, step is one
A[1:3:1]

array([2, 3])

Array slices are *mutable*: if they are assigned a new value the original array from which the slice was extracted is modified:

In [50]:
A[1:3:1] = [-2,-3]
A

array([ 1, -2, -3,  4,  5])

We can omit any of the three parameters in `M[lower:upper:step]`, by default `lower` is the beginning , `upper` is the end of the array, and `step` is one

In [52]:
A[::2] # step is 2, lower and upper defaults to the beginning and end of the array

array([ 1, -3,  5])

In [55]:
A[:3] # first three elements

array([ 1, -2, -3])

In [56]:
A[3:] # elements from index 3

array([4, 5])

Negative indices counts from the end of the array:

In [57]:
A[-1] # the last element in the array

5

In [58]:
A[-3:] # the last three elements

array([-3,  4,  5])

In [62]:
A[::-1] #Step backwards, it returns an array with elements in reverse order

array([ 5,  4, -3, -2,  1])

Index slicing works exactly the same way for multidimensional arrays, but every dimension separated by comma:

In [63]:
M

array([[ 1, 20, -1, 40],
       [ 0,  0, -1,  0]])

In [65]:
#a block from the original array
#all rows, two central columns
M[:, 1:3]


array([[20, -1],
       [ 0, -1]])

In [66]:
# all row, skiping even columns
M[:, ::2]

array([[ 1, -1],
       [ 0, -1]])

You can master your **index slicing** abilities by resolving the exercises at the end of this
notebook

** Comparison operators and value testing **

Boolean comparisons can be used to compare members elementwise on arrays of equal size.

In [68]:
a = np.array([1, 3, 0], float) 
b = np.array([0, 3, 2], float) 
print a > b 
print a == b 
print a <= b 

[ True False False]
[False  True False]
[False  True  True]


In [69]:
a = np.array([1, 3, 0], float) 
a > 2

array([False,  True, False], dtype=bool)

The <code>any</code> and <code>all</code> operators can be used to determine whether or not any or all elements of a 
Boolean array are true: 

In [70]:
c = np.array([ True, False, False], bool) 
print any(c), all(c)

True False


The ``where`` function forms a new array from two arrays of equivalent size using a Boolean filter  to choose between elements of the two. Its basic syntax is: <br>
<code>where(boolarray, truearray, falsearray)</code>

In [83]:
a = np.array([1, 3, 0], float) 
np.where(a != 0, 1/a, 0) 

/Users/eloi/miniconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:2: RuntimeWarning: divide by zero encountered in divide
  from IPython.kernel.zmq import kernelapp as app


array([ 1.        ,  0.33333333,  0.        ])

** Indexing with other arrays  (*Fancy indexing*)** 

Arrays allow for a more sophisticated kind of indexing: you can index an array with another array, and in particular with an array of boolean values.  This is particluarly useful to **filter**
information from an array that matches a certain condition.

In [84]:
print arr
row_indices = [1, 2, 3]
arr[row_indices]

[10  1 30 40]


array([ 1, 30, 40])

In [85]:
mask = arr < 9 # construct a boolean array 
               #where i-th eleement is True if the i-th element of arr is less than 9
mask

array([False,  True, False, False], dtype=bool)

The index mask can be converted to position index using the `where` function

In [86]:
indices = np.where(mask)
indices

(array([1]),)

In [87]:
print 'Values below 9:', arr[mask]

Values below 9: [1]


In [88]:
print 'Resetting all values below 9 to 10...'
arr[mask] = 10
print arr

Resetting all values below 9 to 10...
[10 10 30 40]


It is also possible to select using integer arrays that represent indexes.

In [89]:
a = np.array([2, 4, 6, 8], float) 
b = np.array([0, 0, 1, 3, 2, 1], int)  # the 0th, 0th, 1st, 3rd, 2nd, and 1st elements of a
a[b] 

array([ 2.,  2.,  4.,  8.,  6.,  4.])

For multidimensional arrays, we have to send multiple one-dimensional integer arrays to the 
selection bracket, one for each axis.

In [91]:
a = np.array([[1, 4], [9, 16]], float) 
print a
b = np.array([0, 0, 1, 1, 0], int) 
c = np.array([0, 1, 1, 1, 1], int) 
a[b,c] 

[[  1.   4.]
 [  9.  16.]]


array([  1.,   4.,  16.,  16.,   4.])

## Array Attributes and Methods
The information about the type of an array is contained in its *dtype* attribute:

In [92]:
# arr is an object of the type ndarray that the numpy module provides.
type(arr)

numpy.ndarray

In [93]:
arr.dtype

dtype('int64')

The difference between the `arr` and `M` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [99]:
arr.shape

(4,)

In [100]:
M.shape

(2, 4)

The number of elements in the array is available through the `ndarray.size` property:

In [101]:
M.size

8

Equivalently, we could use the function `numpy.shape` and `numpy.size`

In [102]:
np.shape(M)

(2, 4)

In [103]:
np.size(M)

8

** More atrributes **

In [104]:
arr.itemsize # bytes per element

8

In [105]:
arr.nbytes # number of bytes

32

In [106]:
arr.ndim # number of dimensions

1

** Useful Methods **

NumPy offers a large library of common mathematical functions that can be applied elementwise to arrays. Among these are the functions: <code> abs,sign, sqrt, log, log10, exp, sin, cos, tan, arcsin, arccos, arctan, sinh, cosh, tanh, arcsinh, arccosh, </code> and <code>arctanh </code>. 


In [107]:
a = np.array([1, 4, 9], float) 
np.sqrt(a)

array([ 1.,  2.,  3.])

In [108]:
print 'Minimum and maximum             :', a.min(), a.max()
print 'Sum and product of all elements :', a.sum(), a.prod()
print 'Mean and standard deviation     :', a.mean(), a.std()

Minimum and maximum             : 1.0 9.0
Sum and product of all elements : 14.0 36.0
Mean and standard deviation     : 4.66666666667 3.29983164554


If we want to know which index is the maximum or minimum, it can be done using `argmax` and `argmin`

In [109]:
np.argmax(a)

2

For these methods, the above operations area all computed on all the elements of the array.  But for a multidimensional array, it's possible to do the computation along a single dimension, by passing the `axis` parameter; for example:

In [110]:
print 'For the following array:\n', M
print 'The sum of elements along the rows is    :', M.sum(axis=1)
print 'The sum of elements along the columns is :', M.sum(axis=0)

For the following array:
[[ 1 20 -1 40]
 [ 0  0 -1  0]]
The sum of elements along the rows is    : [60 -1]
The sum of elements along the columns is : [ 1 20 -2 40]


To find unique values in array, we can use the `unique` function:

In [111]:
print arr
np.unique(arr)

[10 10 30 40]


array([10, 30, 40])

### Reshaping, resizing and stacking arrays

The shape of an Numpy array can be modified without copying the underlaying data, which makes it a fast operation even for large arrays.

In [112]:
print M
n, m = M.shape
n,m

[[ 1 20 -1 40]
 [ 0  0 -1  0]]


(2, 4)

In [113]:
B = M.reshape((1,n*m))
print B.shape
B

(1, 8)


array([[ 1, 20, -1, 40,  0,  0, -1,  0]])

In [114]:
B[0,0:4] = 5 # modify the array
B

array([[ 5,  5,  5,  5,  0,  0, -1,  0]])

In [115]:
M # and the original variable is also changed. B is only a different view of the same data

array([[ 5,  5,  5,  5],
       [ 0,  0, -1,  0]])

Using function `repeat`, `tile`, `vstack`, `hstack`, and `concatenate` we can create larger vectors and matrices from smaller ones:

In [116]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [117]:
# repeat each element 3 times
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [118]:
# tile the matrix 3 times 
np.tile(a, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [119]:
np.concatenate((a, np.array([[5, 6]])), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

For transposing a matrix, it can be done using the array property T :

In [120]:
np.concatenate((a, np.array([[5, 6]]).T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

**hstack** and **vstack** : shortcuts for concatenate horizontally and vertically

In [121]:
np.vstack((a,np.array([[5, 6]])))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [122]:
np.hstack((a,np.array([[5, 6]]).T))

array([[1, 2, 5],
       [3, 4, 6]])

## Copy and "deep copy"

To achieve high performance, assignments in Python usually do not copy the underlaying objects. This is important for example when objects are passed between functions, to avoid an excessive amount of memory copying when it is not necessary (techincal term: pass by reference).

In [123]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [124]:
# now B is referring to the same array data as A 
B = A 

In [125]:
# changing B affects A
B[0,0] = 10
B

array([[10,  2],
       [ 3,  4]])

In [126]:
A

array([[10,  2],
       [ 3,  4]])

If we want to avoid this behavior, so that when we get a new completely independent object B copied from A, then we need to do a so-called "deep copy" using the function copy:

In [127]:
B = np.copy(A)

In [128]:
# now, if we modify B, A is not affected
B[0,0] = -5
B

array([[-5,  2],
       [ 3,  4]])

In [129]:
A

array([[10,  2],
       [ 3,  4]])

## Operating with arrays
Arrays support all regular arithmetic operators, and the numpy library also contains a complete collection of basic mathematical functions that operate on arrays.  It is important to remember that in general, all operations with arrays are applied *element-wise*, i.e., are applied to all the elements of the array at the same time. 

In [130]:
v1 = np.arange(0, 4)
v1

array([0, 1, 2, 3])

In [131]:
v1 * 2

array([0, 2, 4, 6])

In [132]:
v1 + 2

array([2, 3, 4, 5])

In [133]:
M*2

array([[10, 10, 10, 10],
       [ 0,  0, -2,  0]])

When we add, subtract, multiply and divide arrays with each other, the default behaviour is **element-wise** operations:

In [134]:
print M
M*M

[[ 5  5  5  5]
 [ 0  0 -1  0]]


array([[25, 25, 25, 25],
       [ 0,  0,  1,  0]])

In [135]:
v1*v1

array([0, 1, 4, 9])

If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:

In [136]:
M.shape, v1.shape

((2, 4), (4,))

In [137]:
M * v1

array([[ 0,  5, 10, 15],
       [ 0,  0, -2,  0]])

What about matrix mutiplication?  We can  use the `dot` function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments: 

In [138]:
print M
print v1
np.dot(M,v1)

[[ 5  5  5  5]
 [ 0  0 -1  0]]
[0 1 2 3]


array([30, -2])

In [139]:
np.dot(v1,v1)

14

** Broadcasting **

Broadcasting means that, in principle, arrays must always match in their dimensionality in order for an operation to be valid, numpy will *broadcast* dimensions when possible. Previous examples of operations with an scalar and a vector is broadcasting:

In [142]:
print v1
v1 + 5

[0 1 2 3]


array([5, 6, 7, 8])

We can also broadcast a 1D array to a 2D array, in this case adding a vector to all rows of a matrix:

In [141]:
np.ones((4, 4)) + v1

array([[ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.]])

We can also broadcast in two directions at a time:

In [144]:
print v1.reshape((4, 1))
print np.arange(4)
v1.reshape((4, 1)) + np.arange(4)

[[0]
 [1]
 [2]
 [3]]
[0 1 2 3]


array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

** Rules of Broadcasting **

Broadcasting follows the next algorithm:

1. If the two arrays differ in their number of dimensions, the shape of the array with fewer dimensions is padded with ones on its leading (left) side.

2. If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

Note that all of this happens without ever actually creating the stretched arrays in memory! This broadcasting behavior is in practice enormously powerful, especially because when numpy broadcasts to create new dimensions or to `stretch` existing ones, it doesn't actually replicate the data. 


In the first example: 

    v1 + 5

the operation is carried as if the 5 was a 1-d array with 5 in all of its entries, but no actual array was ever created.

In the example

    v1.reshape((4, 1)) + np.arange(4)
    
- the second array is 'promoted' to a 2-dimensional array of shape (1, 4)
- the second array is 'stretched' to shape (4, 4)
- the first array is 'stretched' to shape (4, 4)

Then the operation proceeds as if on two 4 $\times$ 4 arrays.

In [145]:
np.tile(np.arange(4),(4,1))+ np.tile(v1.reshape((4,1)),4)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [146]:
#Broadcasting unrolled
print np.tile(np.arange(4),(4,1))
print np.tile(v1.reshape((4,1)),4)
np.tile(np.arange(4),(4,1)) +  np.tile(v1.reshape((4,1)),4)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

### Visualizing Broadcasting

<img src="http://www.astroml.org/_images/fig_broadcast_visual_1.png">

([image source](http://www.astroml.org/book_figures/appendix/fig_broadcast_visual.html))

Sometimes, however, we can use the ``newaxis`` constant to specify how we 
want to broadcast:

In [ ]:
a = np.zeros((2,2), float) 
b = np.array([-1., 3.], float) 
print a, b
print
print a + b 
print
print a + b[np.newaxis,:] 
print
print a + b[:,np.newaxis] 

#Further reading

* http://numpy.scipy.org
* http://scipy.org/Tentative_NumPy_Tutorial
* http://scipy.org/NumPy_for_Matlab_Users - A Numpy guide for MATLAB users.

#Exercises

1) In the following table we have expression values for 5 genes at 4 time points. 

In [150]:
from IPython.lib import display
%cat 'genes.csv' 
display.FileLink('genes.csv')


Gene name,4h,12h,24h,48h
A2M,0.12,0.08,0.06,0.02
FOS,0.01,0.07,0.11,0.09
BRCA2,0.03,0.04,0.04,0.02
CPOX,0.05,0.09,0.11,0.14

/Users/eloi/Dropbox/PostGrauDataScience/DataScience-Course2/DataScience2-Numpy-Pandas/genes.csv

   - Create a single array for the data (4x4)
   - Find the mean expression value per gene
   - Find the mean expression value per time point
   - Which gene has the maximum mean expression value? (Use the ``tab`` help on an `array`)

In [ ]:
#Your Code Here

<div class="alert alert-info">`ipythonblocks` is a teaching tool that allows students to experiment with Python flow control concepts and immediately see the effects of their code represented in a colorful, attractive way. BlockGrid objects can be **indexed and sliced like 2D NumPy arrays** making them good practice for learning how to access arrays. </div>

In [151]:
import os
os.chdir('./modules/')
from ipythonblocks import BlockGrid
from ipythonblocks import colors
os.chdir('..')
grid = BlockGrid(8, 8, fill=(123, 234, 123))
grid.show()

In [152]:
a = np.array(np.zeros([8,8],dtype='int64'))
a

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [153]:
grid[0, 0] #access to [0,0] element

Block(123, 234, 123, size=20)

In [154]:
grid[0:2,:] = colors['Teal']
grid.show()

In [155]:
a[0:2,:] = 1
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [156]:
grid[2,1:] = colors['Blue']
grid.show()

In [157]:
a[2,1:] = 2
a

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 2, 2, 2, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [158]:
grid[:2,2:3] = colors['Peru']
grid.show()

In [159]:
a[:2,2:3] = 3
a

array([[1, 1, 3, 1, 1, 1, 1, 1],
       [1, 1, 3, 1, 1, 1, 1, 1],
       [0, 2, 2, 2, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [160]:
grid[:,::2] = colors['Peru']
grid.show()

In [161]:
a[:,::2] = 4
a

array([[4, 1, 4, 1, 4, 1, 4, 1],
       [4, 1, 4, 1, 4, 1, 4, 1],
       [4, 2, 4, 2, 4, 2, 4, 2],
       [4, 0, 4, 0, 4, 0, 4, 0],
       [4, 0, 4, 0, 4, 0, 4, 0],
       [4, 0, 4, 0, 4, 0, 4, 0],
       [4, 0, 4, 0, 4, 0, 4, 0],
       [4, 0, 4, 0, 4, 0, 4, 0]])

In [162]:
grid[::2,::3] = colors['Red']
grid.show()

In [163]:
a[::2,::3] = 5
a

array([[5, 1, 4, 5, 4, 1, 5, 1],
       [4, 1, 4, 1, 4, 1, 4, 1],
       [5, 2, 4, 5, 4, 2, 5, 2],
       [4, 0, 4, 0, 4, 0, 4, 0],
       [5, 0, 4, 5, 4, 0, 5, 0],
       [4, 0, 4, 0, 4, 0, 4, 0],
       [5, 0, 4, 5, 4, 0, 5, 0],
       [4, 0, 4, 0, 4, 0, 4, 0]])

2) Build a graphical representation of all multiple of 3 numbers from 0 to 49 by using exclusively the slicing operator (no iterations). 

In [ ]:
grid = BlockGrid(50, 1, block_size=10, fill=(123, 234, 123))
grid
# Your solution here

3) Build a graphical representation of a chessboard 8x8 by using exclusively the slicing operator (no iterations).

In [ ]:
grid = BlockGrid(8, 8, block_size=20, fill=(0, 0, 0))
# Your solution here

4) Build a graphical representation of the prime numbers from 0 to 4999. (Hint: Compute the list of prime numbers and map this list to the grid representation).

In [ ]:
BlockGrid(50, 100, block_size=10, fill=(123, 234, 123))
# Your solution here

# Next Notebook session

In [164]:
from IPython.display import FileLink
FileLink('DataScience-Pandas.ipynb')

/Users/eloi/Dropbox/PostGrauDataScience/DataScience-Course2/DataScience2-Numpy-Pandas/DataScience-Pandas.ipynb